---
- name: Create and Configure Web Server
  hosts: all
  become: yes

  tasks:
    - name: Install Apache HTTP Server
      package:
        name: httpd
        state: present

    - name: Start Apache Service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html
      copy:
        content: "<html><body><h1>Welcome to my web server!</h1></body></html>"
        dest: /var/www/html/index.html


    - firewalld: 
        port: 80/tcp 
        state: enabled
        permanent: yes
        immediate: yes   

